import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase options. Replace with values generated by FlutterFire CLI.
/// Run: flutter pub global activate flutterfire_cli && flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        return windows;
      // case TargetPlatform.linux:
      //   return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpY4DDu60MhYIxO9sX7AXXM0i07OJbX1g',
    appId: '1:545672182111:web:2e41523c00a1c09c4fdeea',
    messagingSenderId: '545672182111',
    projectId: 'equawise-c8be2',
    authDomain: 'equawise-c8be2.firebaseapp.com',
    storageBucket: 'equawise-c8be2.firebasestorage.app',
    measurementId: 'G-82JN2CN1BB',
  );

  // Replace all 'REPLACE_ME' values by running `flutterfire configure`.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GUsyTzjmm_M_cpO7N0rvZFJi5B1zHL0',
    appId: '1:545672182111:android:bbd5fa7f174dbdbe4fdeea',
    messagingSenderId: '545672182111',
    projectId: 'equawise-c8be2',
    storageBucket: 'equawise-c8be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOaehaK4PmzKslI-IHoYBvm3YEzQlMeFs',
    appId: '1:545672182111:ios:ca3d555f637e99964fdeea',
    messagingSenderId: '545672182111',
    projectId: 'equawise-c8be2',
    storageBucket: 'equawise-c8be2.firebasestorage.app',
    iosBundleId: 'com.equawise.equawise',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'REPLACE_ME',
  //   appId: 'REPLACE_ME',
  //   messagingSenderId: 'REPLACE_ME',
  //   projectId: 'REPLACE_ME',
  //   storageBucket: 'REPLACE_ME',
  //   iosBundleId: 'REPLACE_ME',
  // );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpY4DDu60MhYIxO9sX7AXXM0i07OJbX1g',
    appId: '1:545672182111:web:91d10193d2058b094fdeea',
    messagingSenderId: '545672182111',
    projectId: 'equawise-c8be2',
    authDomain: 'equawise-c8be2.firebaseapp.com',
    storageBucket: 'equawise-c8be2.firebasestorage.app',
    measurementId: 'G-7GSH0JLFG5',
  );


}
